server:
  port: 8080
name: spring-cloud-gateway


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka/