version: '3.9'

volumes:
  mysql_data:
    driver: local

services:
  mysql:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: mysql_Valhalla
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: keycloak
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

  keycloak:
    container_name: keycloak_valhalla
    image: quay.io/keycloak/keycloak:19.0.2
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_PORT: "3306"
      DB_DATABASE: keycloak
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
      KC_HOSTNAME: "localhost"
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_HTTP_ENABLED: "true"
    command: start --optimized
    ports:
      - "8180:8080"
    depends_on:
      - mysql

  eureka-server:
    image: barathece91/eureka-server-k8s
    ports:
      - "8761:8761"
    environment:
      preferIpAddress: true
    command: mvn clean spring-boot:run

  spring-cloud-gateway-service:
    image: barathece91/eureka-server-k8s
    ports:
        - "8080:8080"
    depends_on:
      - eureka-server
      - keycloak
      - mysql
    environment:
        server.port: 8080
    command: mvn clean spring-boot:run





