server:
  error:
    include-stacktrace: never

spring:
  main:
  datasource:
    url: jdbc:mysql://localhost:3306/keycloak
    USERNAME: "${USERNAME}"
    PASSWORD: "${PASSWORD}"
  jpa:
    hibernate:
      ddl-auto: update


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: when_authorized

spring-doc:
  swagger-ui:
    operations-sorter: method

