server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  application:
    name: eureka-server
  server:
    port: 8761
  eureka:
    client:
      registerWithEureka: false
      fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/keycloak
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update


name: gateway
  cloud:
    gateway:
      routes:
        - id: test-service
          uri: lb://test-service
          predicates:
            - Path=/test/**
port: 8080
  eureka:
    client:
      registerWithEureka: true
      serviceUrl:
        defaultZone: ${EUREKA_SERVER_ADDRESS}


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: when_authorized

spring-doc:
  swagger-ui:
    operations-sorter: method

